server:
  port: 8080
  compression:
    enabled: true
spring:
  cloud:
    refresh:
      enabled: false
  datasource:
    hikari:
      maximum-pool-size: 4
    # ???
    #    url: jdbc:mariadb://14.41.2.189:13306/neos_1234
    #    username: neos
    #    password: neos
    #    driver-class-name: org.mariadb.jdbc.Driver
    # ???
    url: jdbc:log4jdbc:mariadb://localhost:3306/dream
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: 1234

mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  mapper-locations: classpath:mapper/*.xml
logging:
  config: classpath:log4j2.xml

